name: Container

on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"


    steps:
      - name: Post a new user
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"username":"John Doe","address":"Palo alto"}' http://localhost:3001/api/user

      - name: Get all users
        run: |
          curl http://localhost:3001/api/users

      - name: Log node version
        run: |
          node --version
          cat /etc/os-release
          
