name: Container

on: [push]

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: |
          node -v

      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'

      - name: docker Log node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v

      - uses: actions/checkout@v3.5.3

      - name: Make script executable
        run: chmod +x script.sh

      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: 'Some string'

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"

    steps:
      - name: Post a new user
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"username":"John Doe","address":"Palo alto"}' http://localhost:3001/api/user

      - name: Get all users
        run: |
          curl http://localhost:3001/api/users

      - name: Log node version
        run: |
          node --version
          cat /etc/os-release
          
