name: Matrix

on: [push]

jobs:
  node-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [6, 8, 10]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Log node version
        run: node --version
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name : Log node version
        run: node --version
